/* eslint-disable no-process-env */
//Do not edit this file, add grunt tasks to the folder `build/tasks`, this file be overridden every time you run yarn install in jslib-platform
module.exports = function (grunt) {
    'use strict';
    const shell = require('shelljs')
    var pkg = grunt.file.readJSON('package.json');

    grunt.initConfig({
        pkg: pkg,
    });
    grunt.registerTask('ts', function () {
        shell.exec('./node_modules/typescript/bin/tsc');
    })
};
